# t-rex configuration

[service.mvt]
viewer = false

[[datasource]]
dbconn = "sqlite:///Users/zhu/Documents/time2reachtest/data.db"
name = "dbconn"
default = true
connection_timeout=30000000000

[grid]
predefined = "web_mercator"

[[tileset]]
name = "all_cities"

#extent = [ 45.287289604799454, -73.99780596599936,45.74763391904646, -73.35964694939565]
# New York City
#extent = [
#    40.39865884215855,
#    -74.10978944228054,
#
#    41.1118967693351 ,
#    -73.60672750343336
#]

# Vancouver

#extent = [
#    49.14300779025667,
#    -123.26949900034515,
#    49.31936004616406,
#    -122.67464806527876
#]


[[tileset.layer]]
name = "all_cities"
table_name = "all_cities"
geometry_field = "geom"
fid_field="fid"
geometry_type = "LINESTRING"
srid = 4326
buffer_size = 0
#make_valid = true
query_limit = 1000000000


# [cache.s3]
# bucket="timetoreach-tiles"
# access_key="AKIA3DIAOJLS3KMRGIXW"
# secret_key="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"
# region="us-east-1"
# endpoint="s3.us-east-1.amazonaws.com"

[cache.file]
base = "/Users/zhu/Documents/time2reachtest/cache"
baseurl = "http://example.com/tiles"



[webserver]
# Bind address. Use 0.0.0.0 to listen on all adresses.
bind = "0.0.0.0"
port = 6767

